// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: short_alias.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoCache.Tests.pb {

  /// <summary>Holder for reflection information generated from short_alias.proto</summary>
  public static partial class ShortAliasReflection {

    #region Descriptor
    /// <summary>File descriptor for short_alias.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShortAliasReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFzaG9ydF9hbGlhcy5wcm90bxILc2hvcnRfYWxpYXMiGAoJQm9vbEFsaWFz",
            "EgsKA194XxgBIAMoCCIYCglMb25nQWxpYXMSCwoDX3hfGAEgAygDImcKDExv",
            "bmdNYXBBbGlhcxItCgNfeF8YASADKAsyIC5zaG9ydF9hbGlhcy5Mb25nTWFw",
            "QWxpYXMuWEVudHJ5GigKBlhFbnRyeRILCgNrZXkYASABKAMSDQoFdmFsdWUY",
            "AiABKAM6AjgBIoYDCgtBbGlhc0hvbGRlchIlCgVmbGFncxgBIAEoCzIWLnNo",
            "b3J0X2FsaWFzLkJvb2xBbGlhcxIkCgRyb3dzGAIgAygLMhYuc2hvcnRfYWxp",
            "YXMuQm9vbEFsaWFzEjYKB2VudHJpZXMYAyADKAsyJS5zaG9ydF9hbGlhcy5B",
            "bGlhc0hvbGRlci5FbnRyaWVzRW50cnkSJQoFbG9uZ3MYBCABKAsyFi5zaG9y",
            "dF9hbGlhcy5Mb25nQWxpYXMSKwoIbG9uZ19tYXAYBSABKAsyGS5zaG9ydF9h",
            "bGlhcy5Mb25nTWFwQWxpYXMSKQoJbG9uZ19yb3dzGAYgAygLMhYuc2hvcnRf",
            "YWxpYXMuTG9uZ0FsaWFzEisKCG1hcF9yb3dzGAcgAygLMhkuc2hvcnRfYWxp",
            "YXMuTG9uZ01hcEFsaWFzGkYKDEVudHJpZXNFbnRyeRILCgNrZXkYASABKAUS",
            "JQoFdmFsdWUYAiABKAsyFi5zaG9ydF9hbGlhcy5Cb29sQWxpYXM6AjgBQhaq",
            "AhNQcm90b0NhY2hlLlRlc3RzLnBiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoCache.Tests.pb.BoolAlias), global::ProtoCache.Tests.pb.BoolAlias.Parser, new[]{ "X" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoCache.Tests.pb.LongAlias), global::ProtoCache.Tests.pb.LongAlias.Parser, new[]{ "X" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoCache.Tests.pb.LongMapAlias), global::ProtoCache.Tests.pb.LongMapAlias.Parser, new[]{ "X" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoCache.Tests.pb.AliasHolder), global::ProtoCache.Tests.pb.AliasHolder.Parser, new[]{ "Flags", "Rows", "Entries", "Longs", "LongMap", "LongRows", "MapRows" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BoolAlias : pb::IMessage<BoolAlias>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BoolAlias> _parser = new pb::MessageParser<BoolAlias>(() => new BoolAlias());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BoolAlias> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoCache.Tests.pb.ShortAliasReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BoolAlias() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BoolAlias(BoolAlias other) : this() {
      X_ = other.X_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BoolAlias Clone() {
      return new BoolAlias(this);
    }

    /// <summary>Field number for the "_x_" field.</summary>
    public const int XFieldNumber = 1;
    private static readonly pb::FieldCodec<bool> _repeated_X_codec
        = pb::FieldCodec.ForBool(10);
    private readonly pbc::RepeatedField<bool> X_ = new pbc::RepeatedField<bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<bool> X {
      get { return X_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BoolAlias);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BoolAlias other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!X_.Equals(other.X_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= X_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      X_.WriteTo(output, _repeated_X_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      X_.WriteTo(ref output, _repeated_X_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += X_.CalculateSize(_repeated_X_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BoolAlias other) {
      if (other == null) {
        return;
      }
      X_.Add(other.X_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            X_.AddEntriesFrom(input, _repeated_X_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            X_.AddEntriesFrom(ref input, _repeated_X_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LongAlias : pb::IMessage<LongAlias>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LongAlias> _parser = new pb::MessageParser<LongAlias>(() => new LongAlias());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LongAlias> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoCache.Tests.pb.ShortAliasReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LongAlias() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LongAlias(LongAlias other) : this() {
      X_ = other.X_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LongAlias Clone() {
      return new LongAlias(this);
    }

    /// <summary>Field number for the "_x_" field.</summary>
    public const int XFieldNumber = 1;
    private static readonly pb::FieldCodec<long> _repeated_X_codec
        = pb::FieldCodec.ForInt64(10);
    private readonly pbc::RepeatedField<long> X_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> X {
      get { return X_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LongAlias);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LongAlias other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!X_.Equals(other.X_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= X_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      X_.WriteTo(output, _repeated_X_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      X_.WriteTo(ref output, _repeated_X_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += X_.CalculateSize(_repeated_X_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LongAlias other) {
      if (other == null) {
        return;
      }
      X_.Add(other.X_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            X_.AddEntriesFrom(input, _repeated_X_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            X_.AddEntriesFrom(ref input, _repeated_X_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LongMapAlias : pb::IMessage<LongMapAlias>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LongMapAlias> _parser = new pb::MessageParser<LongMapAlias>(() => new LongMapAlias());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LongMapAlias> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoCache.Tests.pb.ShortAliasReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LongMapAlias() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LongMapAlias(LongMapAlias other) : this() {
      X_ = other.X_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LongMapAlias Clone() {
      return new LongMapAlias(this);
    }

    /// <summary>Field number for the "_x_" field.</summary>
    public const int XFieldNumber = 1;
    private static readonly pbc::MapField<long, long>.Codec _map_X_codec
        = new pbc::MapField<long, long>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForInt64(16, 0L), 10);
    private readonly pbc::MapField<long, long> X_ = new pbc::MapField<long, long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, long> X {
      get { return X_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LongMapAlias);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LongMapAlias other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!X.Equals(other.X)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= X.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      X_.WriteTo(output, _map_X_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      X_.WriteTo(ref output, _map_X_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += X_.CalculateSize(_map_X_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LongMapAlias other) {
      if (other == null) {
        return;
      }
      X_.Add(other.X_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            X_.AddEntriesFrom(input, _map_X_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            X_.AddEntriesFrom(ref input, _map_X_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AliasHolder : pb::IMessage<AliasHolder>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AliasHolder> _parser = new pb::MessageParser<AliasHolder>(() => new AliasHolder());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AliasHolder> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoCache.Tests.pb.ShortAliasReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AliasHolder() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AliasHolder(AliasHolder other) : this() {
      flags_ = other.flags_ != null ? other.flags_.Clone() : null;
      rows_ = other.rows_.Clone();
      entries_ = other.entries_.Clone();
      longs_ = other.longs_ != null ? other.longs_.Clone() : null;
      longMap_ = other.longMap_ != null ? other.longMap_.Clone() : null;
      longRows_ = other.longRows_.Clone();
      mapRows_ = other.mapRows_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AliasHolder Clone() {
      return new AliasHolder(this);
    }

    /// <summary>Field number for the "flags" field.</summary>
    public const int FlagsFieldNumber = 1;
    private global::ProtoCache.Tests.pb.BoolAlias flags_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoCache.Tests.pb.BoolAlias Flags {
      get { return flags_; }
      set {
        flags_ = value;
      }
    }

    /// <summary>Field number for the "rows" field.</summary>
    public const int RowsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ProtoCache.Tests.pb.BoolAlias> _repeated_rows_codec
        = pb::FieldCodec.ForMessage(18, global::ProtoCache.Tests.pb.BoolAlias.Parser);
    private readonly pbc::RepeatedField<global::ProtoCache.Tests.pb.BoolAlias> rows_ = new pbc::RepeatedField<global::ProtoCache.Tests.pb.BoolAlias>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtoCache.Tests.pb.BoolAlias> Rows {
      get { return rows_; }
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 3;
    private static readonly pbc::MapField<int, global::ProtoCache.Tests.pb.BoolAlias>.Codec _map_entries_codec
        = new pbc::MapField<int, global::ProtoCache.Tests.pb.BoolAlias>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::ProtoCache.Tests.pb.BoolAlias.Parser), 26);
    private readonly pbc::MapField<int, global::ProtoCache.Tests.pb.BoolAlias> entries_ = new pbc::MapField<int, global::ProtoCache.Tests.pb.BoolAlias>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::ProtoCache.Tests.pb.BoolAlias> Entries {
      get { return entries_; }
    }

    /// <summary>Field number for the "longs" field.</summary>
    public const int LongsFieldNumber = 4;
    private global::ProtoCache.Tests.pb.LongAlias longs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoCache.Tests.pb.LongAlias Longs {
      get { return longs_; }
      set {
        longs_ = value;
      }
    }

    /// <summary>Field number for the "long_map" field.</summary>
    public const int LongMapFieldNumber = 5;
    private global::ProtoCache.Tests.pb.LongMapAlias longMap_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoCache.Tests.pb.LongMapAlias LongMap {
      get { return longMap_; }
      set {
        longMap_ = value;
      }
    }

    /// <summary>Field number for the "long_rows" field.</summary>
    public const int LongRowsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::ProtoCache.Tests.pb.LongAlias> _repeated_longRows_codec
        = pb::FieldCodec.ForMessage(50, global::ProtoCache.Tests.pb.LongAlias.Parser);
    private readonly pbc::RepeatedField<global::ProtoCache.Tests.pb.LongAlias> longRows_ = new pbc::RepeatedField<global::ProtoCache.Tests.pb.LongAlias>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtoCache.Tests.pb.LongAlias> LongRows {
      get { return longRows_; }
    }

    /// <summary>Field number for the "map_rows" field.</summary>
    public const int MapRowsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::ProtoCache.Tests.pb.LongMapAlias> _repeated_mapRows_codec
        = pb::FieldCodec.ForMessage(58, global::ProtoCache.Tests.pb.LongMapAlias.Parser);
    private readonly pbc::RepeatedField<global::ProtoCache.Tests.pb.LongMapAlias> mapRows_ = new pbc::RepeatedField<global::ProtoCache.Tests.pb.LongMapAlias>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtoCache.Tests.pb.LongMapAlias> MapRows {
      get { return mapRows_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AliasHolder);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AliasHolder other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Flags, other.Flags)) return false;
      if(!rows_.Equals(other.rows_)) return false;
      if (!Entries.Equals(other.Entries)) return false;
      if (!object.Equals(Longs, other.Longs)) return false;
      if (!object.Equals(LongMap, other.LongMap)) return false;
      if(!longRows_.Equals(other.longRows_)) return false;
      if(!mapRows_.Equals(other.mapRows_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (flags_ != null) hash ^= Flags.GetHashCode();
      hash ^= rows_.GetHashCode();
      hash ^= Entries.GetHashCode();
      if (longs_ != null) hash ^= Longs.GetHashCode();
      if (longMap_ != null) hash ^= LongMap.GetHashCode();
      hash ^= longRows_.GetHashCode();
      hash ^= mapRows_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (flags_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Flags);
      }
      rows_.WriteTo(output, _repeated_rows_codec);
      entries_.WriteTo(output, _map_entries_codec);
      if (longs_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Longs);
      }
      if (longMap_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LongMap);
      }
      longRows_.WriteTo(output, _repeated_longRows_codec);
      mapRows_.WriteTo(output, _repeated_mapRows_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (flags_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Flags);
      }
      rows_.WriteTo(ref output, _repeated_rows_codec);
      entries_.WriteTo(ref output, _map_entries_codec);
      if (longs_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Longs);
      }
      if (longMap_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LongMap);
      }
      longRows_.WriteTo(ref output, _repeated_longRows_codec);
      mapRows_.WriteTo(ref output, _repeated_mapRows_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (flags_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Flags);
      }
      size += rows_.CalculateSize(_repeated_rows_codec);
      size += entries_.CalculateSize(_map_entries_codec);
      if (longs_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Longs);
      }
      if (longMap_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LongMap);
      }
      size += longRows_.CalculateSize(_repeated_longRows_codec);
      size += mapRows_.CalculateSize(_repeated_mapRows_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AliasHolder other) {
      if (other == null) {
        return;
      }
      if (other.flags_ != null) {
        if (flags_ == null) {
          Flags = new global::ProtoCache.Tests.pb.BoolAlias();
        }
        Flags.MergeFrom(other.Flags);
      }
      rows_.Add(other.rows_);
      entries_.Add(other.entries_);
      if (other.longs_ != null) {
        if (longs_ == null) {
          Longs = new global::ProtoCache.Tests.pb.LongAlias();
        }
        Longs.MergeFrom(other.Longs);
      }
      if (other.longMap_ != null) {
        if (longMap_ == null) {
          LongMap = new global::ProtoCache.Tests.pb.LongMapAlias();
        }
        LongMap.MergeFrom(other.LongMap);
      }
      longRows_.Add(other.longRows_);
      mapRows_.Add(other.mapRows_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (flags_ == null) {
              Flags = new global::ProtoCache.Tests.pb.BoolAlias();
            }
            input.ReadMessage(Flags);
            break;
          }
          case 18: {
            rows_.AddEntriesFrom(input, _repeated_rows_codec);
            break;
          }
          case 26: {
            entries_.AddEntriesFrom(input, _map_entries_codec);
            break;
          }
          case 34: {
            if (longs_ == null) {
              Longs = new global::ProtoCache.Tests.pb.LongAlias();
            }
            input.ReadMessage(Longs);
            break;
          }
          case 42: {
            if (longMap_ == null) {
              LongMap = new global::ProtoCache.Tests.pb.LongMapAlias();
            }
            input.ReadMessage(LongMap);
            break;
          }
          case 50: {
            longRows_.AddEntriesFrom(input, _repeated_longRows_codec);
            break;
          }
          case 58: {
            mapRows_.AddEntriesFrom(input, _repeated_mapRows_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (flags_ == null) {
              Flags = new global::ProtoCache.Tests.pb.BoolAlias();
            }
            input.ReadMessage(Flags);
            break;
          }
          case 18: {
            rows_.AddEntriesFrom(ref input, _repeated_rows_codec);
            break;
          }
          case 26: {
            entries_.AddEntriesFrom(ref input, _map_entries_codec);
            break;
          }
          case 34: {
            if (longs_ == null) {
              Longs = new global::ProtoCache.Tests.pb.LongAlias();
            }
            input.ReadMessage(Longs);
            break;
          }
          case 42: {
            if (longMap_ == null) {
              LongMap = new global::ProtoCache.Tests.pb.LongMapAlias();
            }
            input.ReadMessage(LongMap);
            break;
          }
          case 50: {
            longRows_.AddEntriesFrom(ref input, _repeated_longRows_codec);
            break;
          }
          case 58: {
            mapRows_.AddEntriesFrom(ref input, _repeated_mapRows_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
